//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_negociacao
    {
        public tb_negociacao()
        {
            this.tb_pagamento = new HashSet<tb_pagamento>();
        }
    
        public int id { get; set; }
        public double valor { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
        public Nullable<System.DateTime> validadeProposta { get; set; }
        public Nullable<float> valorPropostoVendedor { get; set; }
        public Nullable<float> valorPropostoCliente { get; set; }
        public string observacao { get; set; }
        public int idTipoNegociacao { get; set; }
        public int idBem { get; set; }
        public int idPessoaCliente { get; set; }
        public int idPessoaVendedor { get; set; }
    
        public virtual tb_bem tb_bem { get; set; }
        public virtual tb_pessoa tb_pessoa { get; set; }
        public virtual tb_pessoa tb_pessoa1 { get; set; }
        public virtual tb_tiponegociacao tb_tiponegociacao { get; set; }
        public virtual ICollection<tb_pagamento> tb_pagamento { get; set; }
    }
}
