//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cor
    {
        public tb_cor()
        {
            this.tb_veiculo = new HashSet<tb_veiculo>();
        }
    
        public int id { get; set; }
        public string tipoCor { get; set; }
        public string cor { get; set; }
    
        public virtual ICollection<tb_veiculo> tb_veiculo { get; set; }
    }
}
