//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_custo
    {
        public int id { get; set; }
        public float valor { get; set; }
        public int idPessoa { get; set; }
        public int idTipoCusto { get; set; }
        public int idBem { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual tb_bem tb_bem { get; set; }
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_pessoa tb_pessoa { get; set; }
        public virtual tb_tipocusto tb_tipocusto { get; set; }
    }
}
