//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagamento
    {
        public int id { get; set; }
        public int idNegociacao { get; set; }
        public int idFormaPagamento { get; set; }
        public Nullable<float> valor { get; set; }
        public float valorPago { get; set; }
        public Nullable<float> juro { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> dataPagamento { get; set; }
    
        public virtual tb_formapagamento tb_formapagamento { get; set; }
        public virtual tb_negociacao tb_negociacao { get; set; }
    }
}
