//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipocusto
    {
        public tb_tipocusto()
        {
            this.tb_custo = new HashSet<tb_custo>();
        }
    
        public int id { get; set; }
        public string tipoCusto { get; set; }
    
        public virtual ICollection<tb_custo> tb_custo { get; set; }
    }
}
