//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipopessoa
    {
        public tb_tipopessoa()
        {
            this.tb_pessoa = new HashSet<tb_pessoa>();
        }
    
        public int id { get; set; }
        public string tipoPessoa { get; set; }
    
        public virtual ICollection<tb_pessoa> tb_pessoa { get; set; }
    }
}
