//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tiponegociacao
    {
        public tb_tiponegociacao()
        {
            this.tb_negociacao = new HashSet<tb_negociacao>();
        }
    
        public int id { get; set; }
        public string tipoNegociacao { get; set; }
    
        public virtual ICollection<tb_negociacao> tb_negociacao { get; set; }
    }
}
