//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_veiculo
    {
        public string id { get; set; }
        public string placa { get; set; }
        public string chassi { get; set; }
        public int idConcessionaria { get; set; }
        public int idModelo { get; set; }
        public int idCor { get; set; }
        public int idBem { get; set; }
        public int idEmpresa { get; set; }
        public Nullable<int> lote { get; set; }
    
        public virtual tb_bem tb_bem { get; set; }
        public virtual tb_cor tb_cor { get; set; }
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_modelo tb_modelo { get; set; }
    }
}
